"""Update models nullables

Revision ID: d1426abed5b8
Revises: 7a969ce470a2
Create Date: 2023-08-31 23:55:29.251524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1426abed5b8'
down_revision = '7a969ce470a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
