"""Add api_id col to models

Revision ID: fedd9da55dc6
Revises: fe6690ab1441
Create Date: 2023-09-06 21:51:36.266268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedd9da55dc6'
down_revision = 'fe6690ab1441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###
