"""remove nullable true in api ids

Revision ID: 4d1ebefaf6e1
Revises: 593c5c3624e9
Create Date: 2023-09-07 01:12:49.916724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1ebefaf6e1'
down_revision = '593c5c3624e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('genre_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('classification_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('classification_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('genre_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('artist_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('venue_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('venue_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('artist_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('genre_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('classification_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('classification_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('genre_api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
