"""add images to artist

Revision ID: 593c5c3624e9
Revises: 6f085dad4dc7
Create Date: 2023-09-06 23:15:31.455986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593c5c3624e9'
down_revision = '6f085dad4dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
