"""Add qty to purchases

Revision ID: de03e03fa23e
Revises: 4d1ebefaf6e1
Create Date: 2023-09-21 08:51:18.361074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de03e03fa23e'
down_revision = '4d1ebefaf6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
