"""add api_ids to models

Revision ID: 6f085dad4dc7
Revises: fedd9da55dc6
Create Date: 2023-09-06 23:02:52.895573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f085dad4dc7'
down_revision = 'fedd9da55dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_api_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('classification_api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_api_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('genre_api_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('artist_api_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('venue_api_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_api_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('classification_api_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('venue_api_id')
        batch_op.drop_column('artist_api_id')
        batch_op.drop_column('genre_api_id')
        batch_op.drop_column('classification_api_id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('classification_api_id')
        batch_op.drop_column('genre_api_id')

    # ### end Alembic commands ###
